[custom]

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;显示IP归属地应用伪装：支持
;AI包括：OpenAI、Claude、Gemini、Copilot、Perplexity

;设置规则标志位
ruleset=👨‍💻 GitHub,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🎯 国内流量,https://ghuc.c-1o.top/cutethotw/ClashRule/main/Rule/Inside.list
ruleset=🎯 国内流量,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
ruleset=🚀 国外流量,https://ghuc.c-1o.top/cutethotw/ClashRule/main/Rule/Outside.list
ruleset=🧚 AI,https://ghuc.c-1o.top/cutethotw/ClashRule/main/Rule/ChatGPT.list
ruleset=🧚 AI,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=🧚 AI,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
ruleset=🧚 AI,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
ruleset=🧚 AI,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
ruleset=🧚 AI,https://ghuc.c-1o.top/cutethotw/ClashRule/main/Rule/Perplexity.list
ruleset=🎯 国内流量,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
ruleset=🎯 国内流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🚀 国外流量,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml
ruleset=🛸 IP归属地伪装,clash-classic:https://ghuc.c-1o.top/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml
;ruleset=🛑 广告拦截,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🛑 广告拦截,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🛑 广告拦截,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
;ruleset=🛑 广告拦截,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
;ruleset=🛑 广告拦截,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🛑 广告拦截,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.yaml
ruleset=🍎 AppleTV,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/cutethotw/ClashRule/main/Rule/Emby.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml
ruleset=📺 Bilibili,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Bilibili,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🎵 Spotify,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
ruleset=🎶 TikTok,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
ruleset=🌏 国内媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
ruleset=📢 谷歌FCM,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 国内流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=Ⓜ️ 微软云盘,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
ruleset=Ⓜ️ 微软服务,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
ruleset=🍎 苹果服务,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
ruleset=🚀 国外流量,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
ruleset=🚀 国外流量,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml
ruleset=🚀 国外流量,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
; ruleset=📹 YouTube,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
; ruleset=🎥 Netflix,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
; ruleset=🐹 DisneyPlus,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
; ruleset=📽️ PrimeVideo,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml
; ruleset=🎦 HBO,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
; ruleset=🎦 HBO,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.yaml
; ruleset=🎦 HBO,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.yaml
; ruleset=🍎 AppleTV,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml
; ruleset=🎬 EMBY,clash-classic:https://ghuc.c-1o.top/cutethotw/ClashRule/main/Rule/Emby.yaml
; ruleset=🎬 EMBY,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.yaml
; ruleset=📺 巴哈姆特,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml
; ruleset=📺 Bilibili,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
; ruleset=📺 Bilibili,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
; ruleset=🎵 Spotify,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
; ruleset=🎶 TikTok,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
; ruleset=🌍 国外媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
; ruleset=🌏 国内媒体,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
; ruleset=📢 谷歌FCM,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
; ruleset=🎯 国内流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
; ruleset=Ⓜ️ 微软云盘,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
; ruleset=Ⓜ️ 微软服务,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
; ruleset=🍎 苹果服务,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
; ruleset=📲 Telegram,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
; ruleset=🤖 Discord,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml
; ruleset=🎮 游戏平台,clash-classic:https://ghuc.c-1o.top/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
ruleset=🚀 国外流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 国内流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 国内流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 国内流量,https://ghuc.c-1o.top/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 国内流量,[]GEOIP,LAN
ruleset=🎯 国内流量,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 国外流量`select`[]🔮 负载均衡`[]♻️ 自动选择`[]🔯 故障转移`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=✈️ 手动选择`select`[]🇺🇸 美国`[]🚁 自建节点`[]🏠 家庭IP`[]🇭🇰 香港 高速`[]🇨🇳 台湾 高速`[]🇸🇬 新加坡 高速`[]🇰🇷 韩国 高速`[]🇯🇵 日本 高速`[]🇺🇸 美国 高速`[]🇬🇧 英国 高速`[]🇪🇺 欧洲 高速`[]🇲🇾 东南亚 高速`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇯🇵 日本`[]🇬🇧 英国`[]🇪🇺 欧洲`[]🇲🇾 东南亚
custom_proxy_group=🛩️ 备用选择`select`[]🚁 自建节点`[]🏠 家庭IP`[]🇭🇰 香港 高速`[]🇨🇳 台湾 高速`[]🇸🇬 新加坡 高速`[]🇰🇷 韩国 高速`[]🇯🇵 日本 高速`[]🇺🇸 美国 高速`[]🇬🇧 英国 高速`[]🇪🇺 欧洲 高速`[]🇲🇾 东南亚 高速`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇯🇵 日本`[]🇺🇸 美国`[]🇬🇧 英国`[]🇪🇺 欧洲`[]🇲🇾 东南亚
custom_proxy_group=🚁 自建节点`select`(SelfHost)
custom_proxy_group=🎯 国内流量`select`[]DIRECT`(电信|联通|移动)`[]🚀 国外流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点`
custom_proxy_group=🛸 IP归属地伪装`select`[]🎯 国内流量`(CN|电信|联通|移动)`[]🏠 家庭IP`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 国外流量`[]🎯 国内流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🏠 家庭IP`select`(家)
; custom_proxy_group=🧚 AI`select`[]✈️ 手动选择`[]🛩️ 备用选择`[]🏠 家庭IP`[]🚁 自建节点
; custom_proxy_group=🧚 AI`url-test`!!PROVIDER=juzicloud!!(美|洛杉矶|纽约|US|USA|United States)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🧚 AI`url-test`^(V\d).*(美|洛杉矶|纽约|US|USA|United States)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 国外媒体`select`[]🚀 国外流量`[]🏠 家庭IP`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇯🇵 日本`[]🇺🇸 美国`[]🇬🇧 英国`[]🇪🇺 欧洲`[]🇲🇾 东南亚`(尼日利亚|NG)`(土耳其|TR|Turkey)`(蒙古|MN)`(澳门|MO)`(RU)`(尼泊尔|NP)`(阿塞拜疆)`(孟加拉|BD)`(约旦|JO)`(柬埔寨|KH)`(阿根廷|AR)`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🍎 AppleTV`select`[]🎯 国内流量`[]🚀 国外流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=📺 Bilibili`select`[]🎯 国内流量`[]🇭🇰 香港`[]🇨🇳 台湾`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🎵 Spotify`select`[]🎯 国内流量`(菲律宾|PH)`(巴基斯坦|PK)`(土耳其|TR|Turkey)`(尼日利亚|NG)`[]🚀 国外流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🎶 TikTok`select`[]🚀 国外流量`[]🏠 家庭IP`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🌏 国内媒体`select`[]🎯 国内流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=👨‍💻 GitHub`select`[]🚀 国外流量`[]🎯 国内流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=📢 谷歌FCM`select`[]🎯 国内流量`[]🚀 国外流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🎯 国内流量`[]🚀 国外流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]✈️ 手动选择`[]🚀 国外流量`[]🎯 国内流量`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🍎 苹果服务`select`[]🎯 国内流量`[]🚀 国外流量`[]✈️ 手动选择`[]🛩️ 备用选择`[]🚁 自建节点
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]🏠 家庭IP`[]🎯 国内流量`[]🚀 国外流量
custom_proxy_group=♻️ 自动选择`url-test`(新加坡|SG|韩国|KR|日本|JP)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 故障转移`fallback`(^(?!.*(电信|联通|移动|5x消耗)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡`load-balance`[]🇭🇰 香港 高速`[]🇨🇳 台湾 高速`[]🇸🇬 新加坡 高速`[]🇰🇷 韩国 高速`[]🇯🇵 日本 高速`[]🇺🇸 美国 高速`[]🇬🇧 英国 高速`[]🇪🇺 欧洲 高速`[]🇲🇾 东南亚 高速`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇯🇵 日本`[]🇺🇸 美国`[]🇬🇧 英国`[]🇪🇺 欧洲`[]🇲🇾 东南亚`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港 高速`url-test`((?!.*5x消耗).*((港|HK|Hong Kong).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(港|HK|Hong Kong)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾 高速`url-test`((?!.*5x消耗).*((台|TW|Taiwan).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(台|TW|Taiwan)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡 高速`url-test`((?!.*5x消耗).*((新|坡|狮城|SG|Singapore).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(新|坡|狮城|SG|Singapore)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国 高速`url-test`((?!.*5x消耗).*((韩|首尔|KR|Korea).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(韩|首尔|KR|Korea)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本 高速`url-test`((?!.*5x消耗).*((日|东京|大阪|JP|Japan).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(日|东京|大阪|JP|Japan)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国 高速`url-test`((?!.*5x消耗).*((美|洛杉矶|纽约|US|USA|United States).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(美|洛杉矶|纽约|US|USA|United States)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国 高速`url-test`((?!.*5x消耗).*((英|伦敦|UK|GB|United Kingdom).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(英|伦敦|UK|GB|United Kingdom)))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇪🇺 欧洲 高速`select`((英|法|德|意|西班|葡|荷|比|卢|瑞士|奥|丹|挪|瑞典|芬|冰|爱|波|捷|斯|匈|罗|保|希|UK|FR|DE|IT|ES|PT|NL|BE|LU|CH|AT|DK|NO|SE|FI|IS|IE|PL|CZ|SK|HU|RO|BG|GR|Europe).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(英|法|德|意|西班|葡|荷|比|卢|瑞士|奥|丹|挪|瑞典|芬|冰|爱|波|捷|斯|匈|罗|保|希|UK|FR|DE|IT|ES|PT|NL|BE|LU|CH|AT|DK|NO|SE|FI|IS|IE|PL|CZ|SK|HU|RO|BG|GR|Europe))
custom_proxy_group=🇲🇾 东南亚 高速`select`((菲|泰|越|马|印|新|PH|TH|VN|MY|IN|ID|SG|Philippines|Thailand|Vietnam|Malaysia|India|Indonesia|Singapore).*(IEPL|iepl|IPLC|iplc)|(IEPL|iepl|IPLC|iplc).*(菲|泰|越|马|印|新|PH|TH|VN|MY|IN|ID|SG|Philippines|Thailand|Vietnam|Malaysia|India|Indonesia|Singapore))
custom_proxy_group=🇭🇰 香港`load-balance`((?!.*5x消耗).*(港|HK|Hong Kong))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾`load-balance`((?!.*5x消耗).*(台|TW|Taiwan))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡`url-test`((?!.*5x消耗).*(新|坡|狮城|SG|Singapore))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国`url-test`((?!.*5x消耗).*(韩|首尔|KR|Korea))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`((?!.*5x消耗).*(日|东京|大阪|JP|Japan))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国`url-test`((?!.*5x消耗).*(美|洛杉矶|纽约|US|USA|United States))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国`load-balance`((?!.*5x消耗).*(英|伦敦|UK|GB|United Kingdom))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇪🇺 欧洲`load-balance`((?!.*5x消耗).*(英|法|德|意|西班|葡|荷|比|卢|瑞士|奥|丹|挪|瑞典|芬|冰|爱|波|捷|斯|匈|罗|保|希|UK|FR|DE|IT|ES|PT|NL|BE|LU|CH|AT|DK|NO|SE|FI|IS|IE|PL|CZ|SK|HU|RO|BG|GR|Europe))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇾 东南亚`load-balance`((?!.*5x消耗).*(菲|泰|越|马|印|新|PH|TH|VN|MY|IN|ID|SG|Philippines|Thailand|Vietnam|Malaysia|India|Indonesia|Singapore))`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://ghuc.c-1o.top/cutethotw/ClashRule/main/GeneralClashConfig.yml
